# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'createWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Create(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(440, 234)
        self.checkBoxNDI = QtWidgets.QCheckBox(Form)
        self.checkBoxNDI.setGeometry(QtCore.QRect(40, 40, 92, 23))
        self.checkBoxNDI.setObjectName("checkBoxNDI")
        self.checkBoxCurrent = QtWidgets.QCheckBox(Form)
        self.checkBoxCurrent.setGeometry(QtCore.QRect(40, 70, 92, 23))
        self.checkBoxCurrent.setObjectName("checkBoxCurrent")
        self.checkBoxIMU = QtWidgets.QCheckBox(Form)
        self.checkBoxIMU.setGeometry(QtCore.QRect(40, 130, 92, 23))
        self.checkBoxIMU.setObjectName("checkBoxIMU")
        self.checkBoxFT = QtWidgets.QCheckBox(Form)
        self.checkBoxFT.setGeometry(QtCore.QRect(40, 100, 92, 23))
        self.checkBoxFT.setObjectName("checkBoxFT")
        self.checkBoxMicrophone = QtWidgets.QCheckBox(Form)
        self.checkBoxMicrophone.setGeometry(QtCore.QRect(40, 160, 101, 23))
        self.checkBoxMicrophone.setObjectName("checkBoxMicrophone")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(40, 10, 91, 17))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(300, 10, 91, 17))
        self.label_3.setObjectName("label_3")
        self.buttonBox = QtWidgets.QDialogButtonBox(Form)
        self.buttonBox.setGeometry(QtCore.QRect(120, 200, 166, 25))
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.spinBoxNDI = QtWidgets.QSpinBox(Form)
        self.spinBoxNDI.setGeometry(QtCore.QRect(280, 40, 48, 26))
        self.spinBoxNDI.setObjectName("spinBoxNDI")
        self.spinBoxCurrent = QtWidgets.QSpinBox(Form)
        self.spinBoxCurrent.setGeometry(QtCore.QRect(280, 70, 48, 26))
        self.spinBoxCurrent.setObjectName("spinBoxCurrent")
        self.spinBoxFT = QtWidgets.QSpinBox(Form)
        self.spinBoxFT.setGeometry(QtCore.QRect(280, 100, 48, 26))
        self.spinBoxFT.setObjectName("spinBoxFT")
        self.spinBoxIMU = QtWidgets.QSpinBox(Form)
        self.spinBoxIMU.setGeometry(QtCore.QRect(280, 130, 48, 26))
        self.spinBoxIMU.setObjectName("spinBoxIMU")
        self.spinBoxMicrophone = QtWidgets.QSpinBox(Form)
        self.spinBoxMicrophone.setGeometry(QtCore.QRect(280, 160, 48, 26))
        self.spinBoxMicrophone.setObjectName("spinBoxMicrophone")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.checkBoxNDI.setText(_translate("Form", "NDI"))
        self.checkBoxCurrent.setText(_translate("Form", "Current"))
        self.checkBoxIMU.setText(_translate("Form", "IMU"))
        self.checkBoxFT.setText(_translate("Form", "F/T"))
        self.checkBoxMicrophone.setText(_translate("Form", "Microphone"))
        self.label_2.setText(_translate("Form", "Sensor Type"))
        self.label_3.setText(_translate("Form", "Hz"))
        self.spinBoxCurrent.setMaximum(1e6)
        self.spinBoxMicrophone.setMaximum(1e6)
        self.spinBoxIMU.setMaximum(50)
        self.spinBoxNDI.setMaximum(50)
        self.spinBoxFT.setMaximum(1e6)